name: wf_pr_devlop
on:
  pull_request:
    branches:
      - develop
jobs:
  pr_develop_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: List files
        run: git ls-tree --name-only HEAD
      - name: npm ci
        run: npm ci
      - name: npx htmlhint **/*.html
        run: npx htmlhint **/*.html
      - name: npx stylelint **/*.css
        run: npx stylelint **/*.css
      - name: Build With Parcel
        run: npx parcel build "source/index.html" --dist-dir "dist" --public-url "/"
      - name: Build Image
        run: docker image build . -t imranucp/myapp:latest
      - name: Check Images
        run: docker image ls  
      - name: Login TO Docker
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image on Docker Hub
        run: docker image push imranucp/myapp:latest
      - name: End of Workflow
        run: echo "End of Workflow"